# Generated by Django 3.1.3 on 2020-12-26 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0002_lane_queue_max'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
