# Generated by Django 3.1.3 on 2020-12-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban', '0003_auto_20201226_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='lane',
            name='path',
            field=models.CharField(max_length=25),
        ),
    ]
