# Generated by Django 3.1.3 on 2020-11-09 14:14

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SysID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SysID', models.CharField(default=base.utils.get_random_alphanumeric_string, max_length=36)),
            ],
        ),
    ]
