# Generated by Django 3.1.3 on 2020-11-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysid',
            old_name='SysID',
            new_name='sysID',
        ),
    ]
