# Generated by Django 3.1.3 on 2020-11-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20201109_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
