# Generated by Django 3.1.3 on 2020-11-09 14:29

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20201109_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysid',
            name='sysID',
            field=models.CharField(default=base.models.get_random_alphanumeric_string, max_length=36, unique=True),
        ),
    ]
