# Generated by Django 3.1.3 on 2020-11-10 18:23

import base.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201109_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysid',
            name='sysID',
            field=models.CharField(default=base.utils.get_random_alphanumeric_string, editable=False, max_length=32, unique=True),
        ),
    ]
