# Generated by Django 3.1.3 on 2020-12-03 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201110_1323'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='attachments/')),
                ('foreign_sysID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sysid')),
            ],
        ),
    ]
