# Generated by Django 3.1.3 on 2020-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_attachment_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='created',
        ),
    ]
