# Generated by Django 3.1.3 on 2020-12-03 21:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_attachment_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
