# Generated by Django 3.1.3 on 2020-12-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201203_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysid',
            name='rel_obj_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sysid',
            name='rel_obj_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
