# Generated by Django 3.1.3 on 2020-12-11 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20201211_0850'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysid',
            name='rel_obj_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
