# Generated by Django 3.1.3 on 2020-12-11 18:26

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_sysid_rel_obj_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to='attachments/', validators=[base.validators.validate_file_size]),
        ),
    ]
