# Generated by Django 3.1.3 on 2020-12-15 14:21

import base.models
import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20201211_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='document',
            field=models.FileField(upload_to=base.models.get_attachment_file, validators=[base.validators.validate_file_size]),
        ),
    ]
