# Generated by Django 3.1.3 on 2020-12-23 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201215_0921'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fields', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
