# Generated by Django 3.1.3 on 2020-12-24 13:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_copylist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copylist',
            name='fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, null=True, size=None),
        ),
    ]
