# Generated by Django 3.1.3 on 2020-11-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0023_auto_20201127_0910'),
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkNotesWatcher',
            new_name='Watcher',
        ),
    ]
