# Generated by Django 3.1.3 on 2020-11-27 14:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20201127_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watcher',
            name='watch_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, default=[], max_length=25), size=None),
        ),
    ]
