# Generated by Django 3.1.3 on 2020-11-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201110_1323'),
        ('tracking', '0003_auto_20201127_0938'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WorkNotes',
            new_name='WorkNote',
        ),
    ]
