# Generated by Django 3.1.3 on 2020-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20201127_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='changed_values',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
