# Generated by Django 3.1.3 on 2020-11-27 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_worknote_changed_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worknote',
            name='changed_values',
        ),
        migrations.AddField(
            model_name='worknote',
            name='changed_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
