# Generated by Django 3.1.3 on 2020-11-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20201127_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='changed_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
