# Generated by Django 3.1.3 on 2020-12-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_attachment'),
        ('tracking', '0009_auto_20201130_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worknote',
            name='foreign_sysID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.sysid'),
        ),
    ]
