# Generated by Django 3.1.3 on 2020-12-10 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_auto_20201210_1703'),
        ('tracking', '0011_auto_20201203_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknote',
            name='note_taker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.customer'),
        ),
    ]
