# Generated by Django 3.1.3 on 2020-11-09 18:27

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20201109_0931'),
        ('access', '0002_auto_20201109_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sysID',
            field=models.OneToOneField(default=base.models.SysID.add_new, on_delete=django.db.models.deletion.CASCADE, to='base.sysid'),
        ),
    ]
