# Generated by Django 3.1.3 on 2020-12-07 13:59

import base.models
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0011_auto_20201203_1659'),
        ('access', '0006_auto_20201207_0804'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSMGroup',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.group')),
                ('path', models.CharField(max_length=25, unique=True)),
                ('is_assignment', models.BooleanField(default=False)),
                ('is_approval', models.BooleanField(default=False)),
                ('is_heirarchal', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itms_group_manager', to='access.customer')),
                ('members', models.ManyToManyField(blank=True, related_name='itsm_group_membership', to='access.Customer')),
                ('sysID', models.OneToOneField(default=base.models.SysID.add_new, on_delete=django.db.models.deletion.CASCADE, to='base.sysid')),
            ],
            bases=('auth.group',),
            managers=[
                ('objects', django.contrib.auth.models.GroupManager()),
            ],
        ),
    ]
