# Generated by Django 3.1.3 on 2020-12-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_sysid_rel_obj_model'),
        ('access', '0009_auto_20201210_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sysID',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.sysid'),
        ),
    ]
