# Generated by Django 3.1.3 on 2020-12-15 20:48

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20201215_0921'),
        ('access', '0010_auto_20201211_0939'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('sysID', models.OneToOneField(default=base.models.SysID.add_new, on_delete=django.db.models.deletion.CASCADE, to='base.sysid')),
            ],
        ),
    ]
