# Generated by Django 3.1.3 on 2020-12-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0011_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsmgroup',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='role_membership', to='access.Role'),
        ),
    ]
