# Generated by Django 3.1.3 on 2021-01-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0015_auto_20201222_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='group',
            name='members',
        ),
        migrations.RemoveField(
            model_name='group',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='group',
            name='sysID',
        ),
    ]
