# Generated by Django 3.1.3 on 2021-01-05 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_auto_20210105_1518'),
        ('ticket', '0034_auto_20210105_1518'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
