# Generated by Django 3.1.3 on 2020-11-10 18:23

from django.db import migrations, models
import ticket.utils


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_incident_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.CharField(default=ticket.models.increment_inc_number, max_length=20, unique=True),
        ),
    ]
