# Generated by Django 3.1.3 on 2020-11-11 18:33

from django.db import migrations, models
import django.db.models.deletion
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_auto_20201109_1655'),
        ('ticket', '0007_auto_20201111_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.ticket')),
                ('number', models.CharField(default=ticket.models.increment_req_number, editable=False, max_length=20, unique=True)),
                ('fulfilled', models.DateTimeField(blank=True, null=True)),
                ('fullfillment_notes', models.TextField(blank=True, null=True)),
            ],
            bases=('ticket.ticket',),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='res_reset_pw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='res_unlock_account',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Outage',
            fields=[
                ('ticket_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ticket.ticket')),
                ('number', models.CharField(default=ticket.models.increment_out_number, editable=False, max_length=20, unique=True)),
                ('severity', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('resolved', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('root_cause_set', models.DateTimeField(blank=True, null=True)),
                ('root_cause_desc', models.TextField(blank=True, null=True)),
                ('incidents', models.ManyToManyField(to='ticket.Incident')),
                ('root_cause_assignee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_cause_assignee', to='access.customer')),
                ('root_cause_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_cause_group', to='access.group')),
            ],
            bases=('ticket.ticket',),
        ),
    ]
