# Generated by Django 3.1.3 on 2020-11-16 18:57

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_auto_20201116_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.CharField(default=ticket.models.increment_pwrst_number, max_length=20, unique=True),
        ),
    ]
