# Generated by Django 3.1.3 on 2020-11-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0010_auto_20201116_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
