# Generated by Django 3.1.3 on 2020-11-17 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_auto_20201117_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc_long',
            field=models.TextField(blank=True, default='Text', null=True),
        ),
    ]
