# Generated by Django 3.1.3 on 2020-11-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_auto_20201117_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc_short',
            field=models.CharField(max_length=100),
        ),
    ]
