# Generated by Django 3.1.3 on 2020-11-17 21:02

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_auto_20201117_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='number',
            field=models.CharField(default=ticket.models.increment_inc_number, max_length=20, unique=True),
        ),
    ]
