# Generated by Django 3.1.3 on 2020-11-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_auto_20201117_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='default_value',
            field=models.BooleanField(default=False),
        ),
    ]
