# Generated by Django 3.1.3 on 2020-11-17 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_status_default_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='order_value',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
