# Generated by Django 3.1.3 on 2020-11-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_status_order_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='system_value',
            field=models.BooleanField(default=False),
        ),
    ]
