# Generated by Django 3.1.3 on 2020-11-24 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_status_system_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='default_value',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(blank=True, default=4, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ticket.priority'),
        ),
    ]
