# Generated by Django 3.1.3 on 2020-11-26 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_auto_20201124_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='reopened',
            field=models.IntegerField(default=0),
        ),
    ]
