# Generated by Django 3.1.3 on 2020-11-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_ticket_reopened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='desc_long',
            field=models.TextField(blank=True, null=True),
        ),
    ]
