# Generated by Django 3.1.3 on 2020-11-27 22:20

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20201110_1323'),
        ('ticket', '0023_auto_20201127_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sysID',
            field=models.ForeignKey(default=base.models.SysID.add_new, editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.sysid'),
        ),
    ]
