# Generated by Django 3.1.3 on 2020-12-10 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_auto_20201210_1703'),
        ('ticket', '0024_auto_20201127_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assignment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access.itsmgroup'),
        ),
    ]
