# Generated by Django 3.1.3 on 2020-12-10 22:38

import base.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20201203_1659'),
        ('ticket', '0025_auto_20201210_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='sysID',
            field=models.OneToOneField(default=base.models.SysID.add_new, editable=False, on_delete=django.db.models.deletion.CASCADE, to='base.sysid'),
        ),
    ]
