# Generated by Django 3.1.3 on 2020-12-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_auto_20201211_0939'),
        ('ticket', '0027_auto_20201213_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_by', to='access.customer'),
        ),
    ]
