# Generated by Django 3.1.3 on 2020-12-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0029_auto_20201222_1334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='fullfillment_notes',
            new_name='fulfillment_notes',
        ),
    ]
