# Generated by Django 3.1.3 on 2020-12-23 18:45

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0030_auto_20201223_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='number',
            field=models.CharField(default=ticket.models.increment_out_number, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.CharField(default=ticket.models.increment_req_number, max_length=20, unique=True),
        ),
    ]
