# Generated by Django 3.1.3 on 2020-12-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0031_auto_20201223_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
