# Generated by Django 3.1.3 on 2020-12-24 14:23

from django.db import migrations, models
import ticket.models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0032_auto_20201224_0907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='number',
            field=models.CharField(default=ticket.models.increment_req_number, max_length=20, unique=True),
        ),
    ]
