# Generated by Django 3.1.3 on 2021-01-05 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0016_auto_20210105_1518'),
        ('ticket', '0033_auto_20201224_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outage',
            name='root_cause_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='root_cause_group', to='access.itsmgroup'),
        ),
    ]
